version: "3"
services:
  web_server:
    container_name: web_server
    image: "nginx:1.23.3-alpine"
    restart: always
    labels:
      tier: frontend
      app: web_server
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${INSTALL_PATH}/web/conf/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "${INSTALL_PATH}/web/temp:/var/nginx/temp/:rw"
      - "${INSTALL_PATH}/web/logs:/etc/nginx/logs/:rw"
      - "${INSTALL_PATH}/web/src/mygdh/web:/usr/share/nginx/html/mygdh/web:ro"
      - "${INSTALL_PATH}/web/src/mygdh/html:/usr/share/nginx/html/mygdh/html:ro"
      - "${INSTALL_PATH}/cert/.acme.sh/mygdh.top_ecc/fullchain.cer:/etc/nginx/mygdh.top/cert.crt:ro"
      - "${INSTALL_PATH}/cert/.acme.sh/mygdh.top_ecc/mygdh.top.key:/etc/nginx/mygdh.top/cert.key:ro"
      - "${INSTALL_PATH}/cert/.acme.sh/wx.mygdh.top_ecc/fullchain.cer:/etc/nginx/wx.mygdh.top/cert.crt:ro"
      - "${INSTALL_PATH}/cert/.acme.sh/wx.mygdh.top_ecc/wx.mygdh.top.key:/etc/nginx/wx.mygdh.top/cert.key:ro"
      - "${INSTALL_PATH}/cert/.acme.sh/admin.mygdh.top_ecc/fullchain.cer:/etc/nginx/admin.mygdh.top/cert.crt:ro"
      - "${INSTALL_PATH}/cert/.acme.sh/admin.mygdh.top_ecc/admin.mygdh.top.key:/etc/nginx/admin.mygdh.top/cert.key:ro"
    depends_on:
      - wx_server
      - admin_server
    links:
      - wx_server:wx_server
      - admin_server:admin_server
  wx_server:
    container_name: wx_server
    image: "node:16-alpine"
    restart: always
    labels:
      tier: backend
      app: wx_server
    environment:
      - TZ=Asia/Shanghai
      - RUNNING_MODE=dev
      - HTTPS=true
      - PORT=443
      - MONGODB=mongodb://${MONG0_MYGDH_USERNAME}:${MONG0_MYGDH_PASSWORD}@mygdhdb:27017/mygdh
      - MQ=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@mygdhmq
      - AppId=${WECHAT_APP_ID}
      - AppSecret=${WECHAT_APP_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - SessionExpiresIn=${SESSION_EXPIRES_IN}
      - USER_DEFAULT_AVATAR=${USER_DEFAULT_AVATAR}
    entrypoint:
      - "sh"
      - "-c"
      - "npm install && node server.js"
    ports:
      - "8443:443"
    working_dir: "/app"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - "${INSTALL_PATH}/app/src/mygdh/mygdh-wx:/app"
      - "${INSTALL_PATH}/app/src/mygdh/hyper-rest:/hyper-rest"
      - "${INSTALL_PATH}/cert/.acme.sh/wx.mygdh.top_ecc/wx.mygdh.top.key:/app/.cert/privkey.pem:ro"
      - "${INSTALL_PATH}/cert/.acme.sh/wx.mygdh.top_ecc/fullchain.cer:/app/.cert/fullchain.pem:ro"
    depends_on:
      - mongodb
      - rabbitmq
    links:
      - mongodb:mygdhdb
      - rabbitmq:mygdhmq
  admin_server:
    container_name: admin_server
    image: "node:16-alpine"
    labels:
      tier: backend
      app: admin_server
    environment:
      - TZ=Asia/Shanghai
      - RUNNING_MODE=rest
      - HTTPS=true
      - PORT=443
      - MONGODB=mongodb://${MONG0_MYGDH_USERNAME}:${MONG0_MYGDH_PASSWORD}@mygdhdb:27017/mygdh
      - MQ=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@mygdhmq
      - AppId=${WECHAT_APP_ID}
      - AppSecret=${WECHAT_APP_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - SessionExpiresIn=${SESSION_EXPIRES_IN}
      - USER_DEFAULT_AVATAR=${USER_DEFAULT_AVATAR}
    entrypoint:
      - "sh"
      - "-c"
      - "npm install && node server.js"
    ports:
      - "9443:443"
    working_dir: "/app"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - "${INSTALL_PATH}/app/src/mygdh/mygdh-admin:/app"
      - "${INSTALL_PATH}/app/src/mygdh/hyper-rest:/hyper-rest"
      - "${INSTALL_PATH}/cert/.acme.sh/admin.mygdh.top_ecc/admin.mygdh.top.key:/app/.cert/privkey.pem:ro"
      - "${INSTALL_PATH}/cert/.acme.sh/admin.mygdh.top_ecc/fullchain.cer:/app/.cert/fullchain.pem:ro"
    depends_on:
      - mongodb
      - rabbitmq
    links:
      - mongodb:mygdhdb
      - rabbitmq:mygdhmq
  mongodb:
    container_name: mongodb
    image: "mongo"
    restart: always
    labels:
      tier: backend
      app: mongodb
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONG0_MYGDH_USERNAME=${MONG0_MYGDH_USERNAME}
      - MONG0_MYGDH_PASSWORD=${MONG0_MYGDH_PASSWORD}
    volumes:
      - ${INSTALL_PATH}/db/mongo/data/mygdh:/data/db
      - ${INSTALL_PATH}/db/mongo/backup/mygdh:/backup
      - ${INSTALL_PATH}/db/mongo/job/mygdh:/job
    ports:
      - "28517:27017"
  mongo-express:
    container_name: "mongo-express"
    image: "mongo-express"
    labels:
      tier: data
      app: mongo-express
    restart: always
    ports:
      - "28081:8081"
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=${ME_CONFIG_OPTIONS_EDITORTHEME}
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mygdhdb:27017/
    depends_on:
      - mongodb
    links:
      - mongodb:mygdhdb
  rabbitmq:
    container_name: "rabbitmq"
    image: "rabbitmq:3-management-alpine"
    labels:
      tier: data
      app: rabbitmq
    environment:
      - TZ=Asia/Shanghai
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672"
      - "15672"
  portainer:
    container_name: portainer
    image: "portainer/portainer:alpine"
    restart: always
    ports:
      - 9888:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${INSTALL_PATH}/portainer:/data:rw